version: "3.8"

services:
  app:
    build: .
    container_name: backend
    ports:
      - "8181:8181"
      - "3232:3232"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

volumes:
  app:
